#define FUNC_COMMENT            1
#define FUNC_INCREMENT_PC       2
#define FUNC_DECREMENT_PC       3
#define FUNC_INCREMENT_MC       4
#define FUNC_DECREMENT_MC       5
#define FUNC_RESET_PC           6
#define FUNC_RESET_MC           7
#define FUNC_TOGGLE_DMOD        8
#define FUNC_SET_DMOD_DEG       9
#define FUNC_SET_DMOD_RAD       10
#define FUNC_SET_DMOD_GRD       11
#define FUNC_NEGATE             12
#define FUNC_ENTER              13
#define FUNC_SWAP               14
#define FUNC_PLUS               15
#define FUNC_MINUS              16
#define FUNC_MULTIPLY           17
#define FUNC_DIVIDE             18
#define FUNC_CLEAR_X            19
#define FUNC_SIN                20
#define FUNC_ARCSIN             21
#define FUNC_COS                22
#define FUNC_ARCCOS             23
#define FUNC_TG                 24
#define FUNC_ARCTG              25
#define FUNC_EXP                26
#define FUNC_10X                27
#define FUNC_LG                 28
#define FUNC_LN                 29
#define FUNC_POW                30
#define FUNC_LOG                31
#define FUNC_ROT                32
#define FUNC_X2                 33
#define FUNC_1X                 34
#define FUNC_SQRT               35
#define FUNC_PI                 36
#define FUNC_EE                 37
#define FUNC_BX                 38
#define FUNC_RAND               39
#define FUNC_SEED               40
#define FUNC_WHOLE              41
#define FUNC_FRAC               42
#define FUNC_MAX                43
#define FUNC_ABS                44
#define FUNC_SIGN               45
