#define FUNC_COMMENT            1
#define FUNC_INCREMENT_PC       2
#define FUNC_DECREMENT_PC       3
#define FUNC_INCREMENT_MC       4
#define FUNC_DECREMENT_MC       5
#define FUNC_RESET_PC           6
#define FUNC_RESET_MC           7
#define FUNC_TOGGLE_DMOD        8
#define FUNC_SET_DMOD_DEG       9
#define FUNC_SET_DMOD_RAD       10
#define FUNC_SET_DMOD_GRD       11
#define FUNC_NEGATE             12
#define FUNC_ENTER              13
#define FUNC_SWAP               14
#define FUNC_PLUS               15
#define FUNC_MINUS              16
#define FUNC_MULTIPLY           17
#define FUNC_DIVIDE             18
#define FUNC_CLEAR_X            19
#define FUNC_SIN                20
#define FUNC_ARCSIN             21
#define FUNC_COS                22
#define FUNC_ARCCOS             23
#define FUNC_TG                 24
#define FUNC_ARCTG              25
#define FUNC_EXP                26
#define FUNC_10X                27
#define FUNC_LG                 28
#define FUNC_LN                 29
#define FUNC_POW                30
#define FUNC_LOG                31
#define FUNC_ROT                32
#define FUNC_X2                 33
#define FUNC_1X                 34
#define FUNC_SQRT               35
#define FUNC_PI                 36
#define FUNC_EE                 37
#define FUNC_BX                 38
#define FUNC_RAND               39
#define FUNC_SEED               40
#define FUNC_WHOLE              41
#define FUNC_FRAC               42
#define FUNC_MAX                43
#define FUNC_ABS                44
#define FUNC_SIGN               45
#define FUNC_AND                46
#define FUNC_OR                 47
#define FUNC_XOR                48
#define FUNC_NOT                49
#define FUNC_D2DM               50
#define FUNC_D2DMS              51
#define FUNC_DM2D               52
#define FUNC_DMS2D              53
#define FUNC_D2RAD              54
#define FUNC_RAD2D              55
#define FUNC_MM2IN              56
#define FUNC_IN2MM              57
#define FUNC_M2X                58
#define FUNC_X2M                59
#define FUNC_K_M2X              60
#define FUNC_K_X2M              61
#define FUNC_A_M2X              62
#define FUNC_A_X2M              63
#define FUNC_GOTO               64
#define FUNC_GOSUB              65
#define FUNC_RETURN             66
#define FUNC_MEMSET             67
#define FUNC_MEMSWP             68
#define FUNC_MEXTOX             69
#define FUNC_XTOMEX             70
#define FUNC_MEXTOR             71
#define FUNC_RTOMEX             72
#define FUNC_MEXCLR             73
#define FUNC_TOGGLE_EMOD        74
#define FUNC_STOP               75
